networks:
  microservices-network:
    external: true
    name: microservices-network

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: restaurant-frontend:latest
    container_name: restaurant-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - microservices-network
    environment:
      - API_GATEWAY_HOST=api-gateway
      - API_GATEWAY_PORT=8080
      - SERVER_NAME=localhost
      # WebSocket configuration
      - WEBSOCKET_URL=ws://api-gateway:8080/ws
    volumes:
      - ./logs/nginx:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Xóa external_links vì không cần thiết khi dùng chung network
    # external_links không hoạt động tốt với custom networks
    depends_on: []  # Không cần depends_on vì frontend chỉ proxy requests