networks:
  microservices-network:
    external: true
    name: microservices-network

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    image: restaurant-frontend:dev
    container_name: restaurant-frontend-dev
    ports:
      - "3000:80"    # Only HTTP port for development
    restart: unless-stopped
    networks:
      - microservices-network
    environment:
      - NODE_ENV=development
      - API_GATEWAY_HOST=api-gateway
      - API_GATEWAY_PORT=8080
      - SERVER_NAME=localhost
      # Dev specific
      - NGINX_DEBUG=1
      - LOG_LEVEL=debug
    volumes:
      - ./logs/nginx:/var/log/nginx
      # Mount nginx config (single file approach)
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: []
    # Wait for backend to be ready (optional)
    # depends_on:
    #   - api-gateway